spring:
  datasource:
      url: jdbc:mysql://8.130.43.168:3306/firstproject
      username: root
      password: abC123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    # 163??????smtp.163.com???????
    host: smtp.163.com
    # ????163??
    username: ljz2020comeon@163.com
    # ????????smtp/pop3?????????????????????
    password: LOAVUNUAXCRCZDRA